### ISSUE TITLE
When RTL, Navbar is messed up!

### ISSUE THREAD

**Issue by yooozy** [ComBoot/ComBoot#1]
I think navgation bar elements are not in the correct order 
take a look:
![screenshot from 2014-01-04 17 48 44](https://f.cloud.github.com/assets/5954540/1844932/b5fab2b4-7560-11e3-9f1d-42a80bb31de5.png)
user div should be in the left and logo should be in the right

any ideas on how to fix that?

**Comment by TheZoker** [comment]
I did not work on that for a month, but know I will rework it :)

For your problem:
Im not sure, if bootstrap supports rtl in generall.

The Navbar is build like the example, so I dont think I can really fix it...

**Comment by yooozy** [comment]
I could get a way around it as the following:

pull logo "brand" to the right

```
<div class="navbar-header navbar-left"> to <div class="navbar-header navbar-right"> 
```

FAQ and Members to the right

```
<ul class="nav navbar-nav navbar-left"> to <ul class="nav navbar-nav navbar-right">
```

the login button to the left:

```
<ul class="nav navbar-nav navbar-right"> to <ul class="nav navbar-nav navbar-left">
```

I don't know if this is the proper way but it works!

**Comment by TheZoker** [comment]
Probaly changing the navs from right to left is a good way to set the navbar rtl :)
I wont add it into main theme, because phpBB provides no settings for theme, so either its ltr or rtl :)

Thank you
