### ISSUE TITLE
Funny bootstrap-select glitch

### ISSUE THREAD

**Issue by leoforney** [ComBoot/ComBoot#10]
Hi I was browsing your demo page and I found this out! I have no clue if I put it to @silviomoreto or to you. Just look at this Gyazo gif and click MP4 http://gyazo.com/93c448189758f03968215ee734959b48

**Comment by TheZoker** [comment]
Fun is over, its fixed ;)

I  you find other bugs or have an feature request, let me know :e-mail:

**Comment by silviomoreto** [comment]
:thumbsup:
