### ISSUE TITLE
» Feature Request « Posting user rank banner & Custom smilies

### ISSUE THREAD

**Issue by leoforney** [ComBoot/ComBoot#11]
I have a feature request... on a post it should have a little banner with the user's rank. It should only have one. BTW I like the update with the circle user. It should look something like this http://gyazo.com/11acc95e4571223029a5746c9bf22ed5 Thanks! :D

I also have another one! A custom smily pack like this one http://www.kolobok.us/download.php?view.12 You will have to user a converter... http://gamall-ida.com/f/viewtopic.php?f=3&t=321

Thanks so much! :D

**Comment by TheZoker** [comment]
I will think about the user ranks....

Simlys are not a matter of the theme in phpBB, because there are stored in the /images/ folder and not in the theme folder.
So theres no may to change it with theme....

Please open a new issue for every single feature request ;)

**Comment by leoforney** [comment]
I meant the User's group.

Ok sounds good I will do that next time.

**Comment by TheZoker** [comment]
Yes sorry I mean User Groups too ;)

**Comment by TheZoker** [comment]
Hmm I guess because of the size of the profile part of a post, a badge wouldn't look that good.

On your example, the surrounding of the profile picture is very small, so it does look good, but with a wide profile area, that would look very horrible, dont you think?

**Comment by leoforney** [comment]
Yeah I guess... If you can't do it then I will attempt to do it :D I will try something new though. Is there a phpBB variable that is used to display a user's group? (P.S. I'm not very good at making phpBB styles lol)

**Comment by TheZoker** [comment]
Is that the way you wanted it?
![proboot-badge](https://f.cloud.github.com/assets/1368405/2252857/f043ecc4-9db0-11e3-8777-6bf2e6b77c6e.png)

BTW: What do you think about a rename to "BootBoard"?

Because proBoot is used by another author, who did a theme with Bootstrap 2

**Comment by leoforney** [comment]
Yeah that looks perfect! and also that would be cool but what about "phpStrap" ?

**Comment by TheZoker** [comment]
Yes thats also a great name :)

Hmm....
I cant decide, thats really hard :P

**Comment by Gjeep** [comment]
How about phpBBoot3 to long? :)

**Comment by TheZoker** [comment]
Hmm yes its a bit loo long I guess, it should be something short and rememberable ;)
By the way:
The final release is on the way ;)
The fix for ucp will be published soon (not later than weekend I hope) and then there are only little things to fix and then I will add new features if I find something usefull :)

If you have a name idea, please let me know :)

**Comment by MrNut** [comment]
Fixes for UCP have been applied. Requested features have also been applied.
269349e
b270a40
d239ed1723a9e8360200c5da68cf3e2ca6055b76
