### ISSUE TITLE
Responsive bootstrap buttons

### ISSUE THREAD

**Issue by leoforney** [ComBoot/ComBoot#13]
Heeeelooo! I have been doing some reasearch and I reccomend you make responsive grids and rows. http://www.bootply.com/93706 & For rows I reccomend you use the class container fluid for everything... :D :+1:

**Comment by TheZoker** [comment]
You mean the "responsive grids and rows" for the buttons?

Because I think the problem with responsive buttons is, that they are very small on mobile devices and hard to hit...

**Comment by leoforney** [comment]
Yes and can't you just not put them in a grid/row and just use the css code from the link? It works just good but I agree that it is hard to push so you might want to adjust the code. :D

**Comment by TheZoker** [comment]
But what would that change?

If I use the code and adjust it, the buttons would just look like where before.

So what would you expect, that this code changes?

**Comment by leoforney** [comment]
IDK I just messed around with the CSS and look at my forums site https://forums.crystalnetwork.us

**Comment by TheZoker** [comment]
In my opinion they are a little to small and break e.g. the search button group:
![little-buttons](https://f.cloud.github.com/assets/1368405/2252468/8516fc4a-9da9-11e3-891e-3bbc251729ea.png)
Sorry dude :disappointed: 

But there is no reason, why you cannot implement them by your self, as you have done ;)

**Comment by leoforney** [comment]
Yeah I just made something that I just add the class `btn-submit` and it just keeps it the same on every size screen. The only issue is that it looks a little odd. That is why I need to crack open bootstrap and just take a look at the class `btn` :D

**Comment by leoforney** [comment]
@TheZoker Done! I made it so it resizes a little bit on that class but not by much. And it looks pretty normal now.

**Comment by TheZoker** [comment]
What did you fix?

The issue with the search button is still there (at least on your site)

**Comment by leoforney** [comment]
Yeah it's still there for the forum but for the navbar it's pretty normal.
