### ISSUE TITLE
Responsive font-size

### ISSUE THREAD

**Issue by leoforney** [ComBoot/ComBoot#14]
Hello I was researching some things on the internet and I found out how to resize text so it always fits on the page using the viewport! Enjoy http://css-tricks.com/viewport-sized-typography/

**Comment by TheZoker** [comment]
Dont you think the font resize is given by bootstrap yet?

Also the most important devices like iOS and Android are not supported and I dont think, anyone would resize his Chrome Browser window that often, do you?

**Comment by leoforney** [comment]
I don't think so yet.. but it should so very much! And I sometimes do because I have 2 monitors and the other one is used for social (Twitter, phpBB, Wordpress, etc...)

**Comment by yooozy** [comment]
this could work great if we lower threshold, let's try and see!

**Comment by TheZoker** [comment]
In my opinion you could read everything fine, when you view it on your monitor and resize the browser window.

Can you give me a screenshot, in which situation the font should be lager?

**Comment by leoforney** [comment]
@TheZoker 
  No it's just my iOS devices it might need to be a little bit smaller but not by much because it looks like it would fit into the viewport but it doesn't.

**Comment by TheZoker** [comment]
The problem is, that the script you posted above is not compatible to iOS and Android devices ;)
