### ISSUE TITLE
Combo boxes in UCP are partially hiding if active.

### ISSUE THREAD

**Issue by AntonShan** [ComBoot/ComBoot#16]
Combo boxes in UCP are partially hiding if active. I thing it's a problem of CSS attribute _overflow_

**Comment by TheZoker** [comment]
You mean the selectors?
Can you send me a screenshot?

**Comment by AntonShan** [comment]
I don't know how to correct name of this element. Dropdown may be?
http://i6.pixs.ru/storage/2/9/7/Untitled1j_6855540_11172297.jpg
If picture is not available in your country tell me about it via e-mail.

**Comment by TheZoker** [comment]
Yes I know that problem, its caused by the <'dd'> and <'dt'> tags.

I will replace them with a <'div class="col-md-x"'> in the next days (I think will be finished next week, because I have to change hole code).

Thank you

**Comment by MrNut** [comment]
Hey, can you confirm that this has been fixed with the latest versions?

**Comment by TheZoker** [comment]
Yes it's fixed.
