### ISSUE TITLE
When RTL, Navbar is messed up!

### ISSUE THREAD

**Issue by yooozy** [ComBoot/ComBoot#2]
I guess the elements are not in correct order take a look:

![screenshot from 2014-01-04 17 48 44](https://f.cloud.github.com/assets/5954540/1845065/836b8520-756b-11e3-9ed1-ee5941126ca3.png)

the user button should be in the left as and the logo in the right

how to get over this?

thanks

**Comment by TheZoker** [comment]
Duplicate of #1
