### ISSUE TITLE
Someone Selling Your Theme

### ISSUE THREAD

**Issue by estin1985** [ComBoot/ComBoot#20]
Not sure if this is you, but if its not you should know someone took your work and is selling it on themeforest.net

http://themeforest.net/item/bboots-html5css3-fully-responsive-phpbb3-theme/6043477

**Comment by dimitrivisser** [comment]
shocking, this member seems to be from Canada, while I am almost sure the owner of pro boot lives in Germany….   519 sales x $ 15 is very nice for something you didn’t write yourself…

**Comment by ck-ws** [comment]
Not sure it's the same, some design and especially the responsiveness is remarkably different from this project.

**Comment by dimitrivisser** [comment]
It’s easy to change some colours and change the behaviour of columns when changing viewports. Even I can do this…  Maybe the author of pro boot should look himself.

It does show the potential of a bootstrap based phpbb theme. Over 500 sales in half a year is not bad.

**Comment by estin1985** [comment]
You can compare the source files using something like diffnow.com, they are identical.

**Comment by MrNut** [comment]
Hi,

Thanks for your concern, but I do believe that Ch-K is correct, this isn't the same theme :)
However, Myself and Zoker will do proper investigation following this.
Thanks,
Mr_Nut

**Comment by ck-ws** [comment]
@estin1985 What did you compare? Have checked some files in template/, none of them are identical.
@MrNut I hope I was right, whould be a shame otherwise.

**Comment by MrNut** [comment]
@ch-k Indeed, I do hope you were right too. 
@estin1985 What did you compare?

**Comment by estin1985** [comment]
if I am wrong, I apologize. I was only trying to help, I have seen it before and it disgusts me how much people steal others work.

**Comment by MrNut** [comment]
@estin1985 That's no problem :) We'd rather be safe than sorry. And yes, unfortunately in today's society it's a very hard thing to stop unless you have the proper measures in place to do so.
But again, thank you for your concern :)
I'll go ahead and close this.

**Comment by TheZoker** [comment]
Hi there,

@estin1985 Thank you very much for you indication.
The author of this theme did create his theme a long time ago and is not connected with my theme.

While the themeforest theme did a long time only base on bootstrap 2, I decided to write a own theme based on bootstrap 3. Also my aim is to offer my theme for free!

So thank you again for your post and do not hesitate to send me a message or leave me a post, when you find something like this.

Regards 
Zoker (aka Florian)

---

> Note: The version 1.0 of this theme will be available soon with a huge amount of new feautres and enhancements. 
> - For a list of coming features, have a look at the changelog: http://zoker.me/go/proboot-changelog
> - To get an email notification, when the new version (and future releases) are available, subscribe to the newsletter (only update emails will be send!): http://zoker.me/go/proboot-newsletter
> 
> Additional there will be a support center!
