### ISSUE TITLE
Included colorpicker js / css which is not existing

### ISSUE THREAD

**Issue by kremsy** [ComBoot/ComBoot#21]
In the overall-header get's an javascript/css file named colorpicker included which is not existing in the theme-folder

**Comment by TheZoker** [comment]
This will be fixed in release 1.0. For now, just remove the two lines.
See #18 

---

> Note: The version 1.0 of this theme will be available soon with a huge amount of new feautres and enhancements. 
> - For a list of coming features, have a look at the changelog: http://zoker.me/go/proboot-changelog
> - To get an email notification, when the new version (and future releases) are available, subscribe to the newsletter (only update emails will be send!): http://zoker.me/go/proboot-newsletter
> 
> Additional there will be a support center!
