### ISSUE TITLE
Fork of proBoot

### ISSUE THREAD

**Issue by Clausi** [ComBoot/ComBoot#22]
Hey,
I am currently working on a fork of your proBoot3 theme for phpBB3. I want to use it as a guilds forum theme (see https://github.com/Clausi/tenetheme )
As there is no license viewed on your project, am I allowed to use and change your code? I will point to your original project in the forums footer.

Best regards 
Clausi

**Comment by TheZoker** [comment]
Hi Clausi,

Thanks for contacting me!
At first I would recommend you to wait a few days for the release of the stable version 1.0, which will change about 174 files. 
I know I promised to publish it some month ago, but for some reasons I had to delay it.

It will also contain a new license, where you are allowed to fork, but forced to keep a back-link on every information page (like github readme file, footer copyright, "Based on" parameter in phpBB settings, phpBB.com release information etc.)

So you can use it, but (like you mentioned) only with back-links.

If you give me any contact information, we can talk about it (skype, hangout etc.)

Kind regards,
Zoker

**Comment by Clausi** [comment]
Thanks for your quick answer. Sounds nice, I will wait for your release.

**Comment by TheZoker** [comment]
It will probably will be this lincens http://creativecommons.org/licenses/by-nc-sa/4.0/

Is there any way I can contact you (skype, hangout, email etc)?

**Comment by dimitrivisser** [comment]
Hi,

Is there any chance for the 1.0 version to be released in the near future ?  I expected it already some months ago, and was really happy to hear 3 weeks ago that it would take only a few days ;-)

**Comment by TheZoker** [comment]
Hi :)

I guess todays your lucky day :smile: 

Version 1.0 was just released this hour!
Hope you can enjoy it :)

Would be glade, if you could give me feedback and let me know about issues.

Have a great weekend!
