### ISSUE TITLE
reCaptcha https support

### ISSUE THREAD

**Issue by tresf** [ComBoot/ComBoot#23]
The following lines have hard-coded `http://` url values which makes reCaptcha scripts break on most browsers that have loaded the page via `https://`.

[`captcha_recaptcha.html#L26`](https://github.com/TheZoker/ComBoot/blob/master/template/captcha_recaptcha.html#L26) and [`captcha_recaptcha.html#L36`](https://github.com/TheZoker/ComBoot/blob/master/template/captcha_recaptcha.html#L36)

For now, we've managed to circumvent this problem by hosting a custom version with the protocol-specific `http:` removed (implying the protocol the page was loaded in).
 [`lmms.io/ ... /captcha_recaptcha.html`](https://github.com/LMMS/lmms.io/blob/master/forum/style/template/captcha_recaptcha.html)

I'm not very good with the phpBB template engine, but it appears the proper way to do this is to detect HTTPS and switch accordingly (after observing phpBB's recaptcha class, it seems to do this internally), but I chose not to in fear of combining php and template vars improperly, so we're just using the URL without the protocol.

Note this problem exists on both `master` branch as well as `phpBB-3.1` branch.

**Comment by TheZoker** [comment]
Hi Tres Finocchiaro,

Thank you for your bug report.
I reviewed your request and your right!

In phpBB there is a own variable for that purpose called `{RECAPTCHA_SERVER}`

I will push the change right now, so you can directly test it.
Please let me know, if that solved your problem!

Have a nice week
Florian

PS: You can ignore the phpBB-3.1 branch for now. Im working on a private branch on the first release candidate for 3.1

PPS: You should also upgrade from proBoot3 (old version) to ComBoot (new version)

**Comment by tresf** [comment]
Tested and working.  Thank you kindly!

**Comment by TheZoker** [comment]
Glad to hear it works :)
Are you going to update to the latest version of ComBoot?
Because it includes a lot of fixes and new features :smile:

Let me know, if there is anything else, I can help you with!

**Comment by tresf** [comment]
> Are you going to update to the latest version of ComBoot?

I'm not even sure what it is in comparison to proboot3 (Sorry, if I posted this bug report in the wrong location...)?

The LMMS team snagged proboot3 to help bring over our old sourceforge phpBB content to our new sponsored hosting.

-Tres

**Comment by TheZoker** [comment]
ComBoot is just the new name of proBoot3. So its simple a name change according to the first stable release of this theme.

So you can update to the latest version (offered here on github) without loosing any feature or anything..

If you unsure, what comboot looks like (it looks almost as proBoot3 does) you can checkout the demo:
http://comboot.de/demo/free/

Hope I could help you :)

If you have any further question, just comment here :)

**Comment by tresf** [comment]
Thanks.  Yes, I tried the demo, it was very nice.

We did customize our version a bit.  I'll drop a line to our team, thank you kindly!
