### ISSUE TITLE
Message Edition randomly bug

### ISSUE THREAD

**Issue by Outkax** [ComBoot/ComBoot#25]
Hello,
I have a phpBB 3.0.13, with the theme COMBOOT. When I create a topic, sometimes it works very well. But sometimes it bug at the message editing. the forum is installed http://dogecoin.fr/forums this address. The bug seems to be random. In the "Forum Commerce", the first subject bug, the second subject "test" do not bug him .. In the forum "A propos du site" the subject bug too. A test account is in place I can provide you the password.

**Comment by TheZoker** [comment]
Would be nice, if you can send me the details here:
http://zoker.me/go/kontakt

Thank you :)

**Comment by Outkax** [comment]
When I try to access the url it gives me this message: "Enter your password to unlock this URL".
I can't access the url.

**Comment by TheZoker** [comment]
Sorry, fixed it :)

**Comment by Outkax** [comment]
Ty :)

**Comment by TheZoker** [comment]
Should be fixed now! Please download the latest version :)

**Comment by Outkax** [comment]
Thank you so much :)

2015-06-27 20:44 GMT+02:00 Florian Gareis notifications@github.com:
