### ISSUE TITLE
BBCode "Code" shows his content in a line

### ISSUE THREAD

**Issue by jslirola** [ComBoot/ComBoot#26]
Hello, the style doesn't show correctly the lines when i try to use a code in a message. Example:

![comboot_code](https://cloud.githubusercontent.com/assets/6697559/7305661/ddc77998-e9ff-11e4-901a-0cca2cf83059.png)

![comboot_code2](https://cloud.githubusercontent.com/assets/6697559/7305681/f7fd5332-e9ff-11e4-9091-e90bd60bbb1c.png)
http://demo.comboot.io/viewtopic.php?style=2&f=2&t=7&p=66#p66

**Comment by TheZoker** [comment]
Seems something is broken with the syntax highlighter. Will fix that asap :)

**Comment by jslirola** [comment]
Do you have any fix?

**Comment by TheZoker** [comment]
I opened a issue here:
https://github.com/PrismJS/prism/issues/598

**Comment by TheZoker** [comment]
Issue should be fixed. Please download the theme (or just the changed files) and replace the current one.

**Comment by jslirola** [comment]
Thank you! It works.
