### ISSUE TITLE
Manage Notifications

### ISSUE THREAD

**Issue by christianhorton** [ComBoot/ComBoot#27]
When you go to User -> User Control Panel -> Manage Notifications, it returns a blank page

**Comment by TheZoker** [comment]
You mean in the phpBB 3.1 demo?
Thats because these files are not converted yet, so they will not work.
But nevertheless, the page is not blank in my browser:
![img_2015 05 31_19h19m49s_018_](https://cloud.githubusercontent.com/assets/1368405/7902904/25b1dcc0-07ca-11e5-96f0-fcaff0b0e4c4.png)

**Comment by christianhorton** [comment]
I am not sure why it wasn't working before, it works now. Thanks

**Comment by TheZoker** [comment]
I did not change anything ;)
