### ISSUE TITLE
Modal - New UPDATE

### ISSUE THREAD

**Issue by DeployIsComing** [ComBoot/ComBoot#29]
Does anybody know where I can remove or disable the Modal showing a new version is available? Even clicking on "Hide Message", "I installed the update" or simply closing the modal, if I refresh the page the modal appear again.

**Comment by TheZoker** [comment]
There is nothing included in this version of comboot.
Do you use the 3.1 version of comboot? Then please post the issue there.

**Comment by DeployIsComing** [comment]
It keeps opening all the time this message: 

I would like to knnow where I can disabled it.

New beta update available
New Version: 1.1-beta4 (04.11.2015)
Your version: 1.1-beta3

Changelog:
- New: User avatar in navbar
- New: Autosize post message
- Update: Colorpicker to 2.3.0
- Update: BS-Select to 1.7.5
- Update: Autosize to 3.0.13
- Improved: notification panel style code
- Fix: Remove duplicate profile info
- Fix: Fix wrong gravatar field type
- Fix: Mobile notification overlap issue
- Fix: Registration page field alignments
- Fix: Poll vote ajax compatibility
- Fix: Notification avatar size on mobile devices
- Fix: Many html 5 issues
- Fix: Firefox mobile align issue
- Fix: Preview image to large
- Fix: Ability to translate online/offline badge
- Fix: Second poll options box below editor
- Fix: Update notification ssl issue
- Fix: Wrong error alert class
- Fix: Topic tools width
- Fix: Topic icon select width
- Fix: Broken pm message view
- Remove angular.js and replace function with nativ jqeury

**Comment by TheZoker** [comment]
This repo is only for version 3.0.x.
Please re-post the issue here, so I can reference it: https://github.com/ComBoot/ComBoot-3.1/issues
