### ISSUE TITLE
add darkstrap

### ISSUE THREAD

**Issue by Digraens** [ComBoot/ComBoot#3]
Hello Zoker.
I would like to
suggest you to add darkstrap to make this
theme look better.

darkstrap source : https://github.com/danneu/darkstrap

**Comment by TheZoker** [comment]
The theme looks great, but is build on boostrap 2, Im using bootstrap 3  for the theme ;)

**Comment by Digraens** [comment]
Just found this on the full request. https://github.com/danneu/darkstrap/pull/22

**Comment by TheZoker** [comment]
danneu put this file to his website and the website is down :/

danneu/darkstrap#23

**Comment by leoforney** [comment]
You can just use http://bootswatch.com ! @TheZoker can you please use Flatly as the default bootswatch.com theme? It looks really nice!!!!

**Comment by TheZoker** [comment]
I will not use darkstrap or flatly as default!

The theme is meant to be compatible to bootstrap 3, so thats the default theme.

But if you want to use your own, just replace the bootstrap.min.css file in the /proBoot3/proBoot3/ (there will be a rename for this theme later on) folder.

So and the end, if this theme will grow out of the beta, you can use whatever you want (bootstrap, bootswatch, darkstrap or any other bootstrap customization)

edit: @iLeoable Here you can see, how it looks with Flatly: http://zoker.me/demo/proBoot3/index.php?theme=flatly

**Comment by TheZoker** [comment]
Additionaly there is no support for panels in darsktrap, so I cannot use it...

**Comment by kungfoochris** [comment]
I just commented on an older issue for this it appears.  I am in the same boat as TheZoker, I use panels throughout so unfortunately no darkstrap for me either.  To bad.  Looks sharp though!
