### ISSUE TITLE
Search Results has no Pagination - 

### ISSUE THREAD

**Issue by trevski** [ComBoot/ComBoot#31]
On the first page of search results you get no navigation stepper for subsequent pages.

I have deployed a heavily modified comboot on an existing site and this is now becoming an issue for my client. Very keen for help with a fix.

**Comment by TheZoker** [comment]
Since I'm 100% working on the 3.1/3.2 version, I have to time to maintain the 3.0 version. So if you want to have a working version, please consider updating your phpBB to 3.1 and download the comboot version for 3.1:
https://comboot.io/blog/beta/beta-3-1/
