### ISSUE TITLE
register captcha image not properly resizing

### ISSUE THREAD

**Issue by byjuchalad** [ComBoot/ComBoot#32]
register captcha image not resizing in chrome or firefox lower versions.

I found changing img{vertical-align:middle;} (phpbb/styles/ComBoot/theme/comboot/bootstrap.min.css) to
img{vertical-align:middle;max-width:100%;height:auto;width:100%;width:auto\9;} this will correct this issue.

I am not tested this in other browsers.  But it is working fine with firefox and chrome.

Can you tell if it is safe to change this css values.

**Comment by TheZoker** [comment]
Since I'm 100% working on the 3.1/3.2 version, I have to time to maintain the 3.0 version. 
If your fixes are working, thats fine! If not, please consider updating your phpBB to 3.1 and download the comboot version for 3.1:
https://comboot.io/blog/beta/beta-3-1/

**Comment by byjuchalad** [comment]
Dear Florian Gareis,

I am working with Phpbb3.1 version only.

I am seriously working with this theme.  I am trying to convert Thanks for
post, and  Reputation system compatibility pack with this theme.

After finishing this task i will update you with a pull request.  I will
also send you the compatibility pack for your approval.

I will be pleased to know whether any Url rewrite and SEO extention
avaliable with this theme?

Thank for you reply

Byju

On Tue, Apr 12, 2016 at 11:10 PM, Florian Gareis notifications@github.com
wrote:

> Since I'm 100% working on the 3.1/3.2 version, I have to time to maintain
> the 3.0 version.
> If your fixes are working, thats fine! If not, please consider updating
> your phpBB to 3.1 and download the comboot version for 3.1:
> https://comboot.io/blog/beta/beta-3-1/
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/ComBoot/ComBoot/issues/32#issuecomment-209023042

## 

"What is your Choice? Violence or Active Nonviolence. Take a Stand now".
Say NO to VIOLENCE, YES to LIFE. Support Peace and active nonviolence.
www.humanistforum.in
www.silo.net
www.geocities.ws/humanist

**Comment by TheZoker** [comment]
Hi Byju,

If you're working with the 3.1, please post your issue there:
https://github.com/ComBoot/ComBoot-3.1/issues

If you need any help with the compatibility packs, let me know!

Currently I'm not aware of any URL/SEO extensions, working with ComBoot. If you have one, test it and let me know, what is not working :)

Regards,
Florian
