### ISSUE TITLE
view topic, index, view forum panel body text align justify instead of left 

### ISSUE THREAD

**Issue by byjuchalad** [ComBoot/ComBoot#34]
This  is a suggestion 
phpbb\styles\ComBoot\theme\comboot\bootstrap.min.css

.panel-body{padding:15px;}  change to 

.panel-body{padding:15px;text-align:justify;}

This looks more appealing for box look

**Comment by TheZoker** [comment]
It's not good practice to change the bootstrap files itself, but you can add that rule to the comboot.css file. That should work
