### ISSUE TITLE
Suggestion for post content block and panel body 

### ISSUE THREAD

**Issue by byjuchalad** [ComBoot/ComBoot#35]
the suggested changes are tried for text justified alignment for mobile devices.
text center alignment for all panel groups and justified alignment for post content panel group is used if screen width is more than 767.  
comboot.js
        if($screenWidth < 767) {
            $navbrandWidth = $screenWidth-$button_width;
        } else {
            $navbrandWidth = 'auto';
            //bp begin 
            $('.panel-body').css('text-align', 'center');
            $('.post-content').css('text-align', 'justify');
            //bp end
        }

**Comment by TheZoker** [comment]
You can always create a pull request for this repo and suggest your changes. I won't add more stuff myself, you can do so (via pull request) and I will approve it and add it:
https://help.github.com/articles/using-pull-requests/
