### ISSUE TITLE
Upload attachment error

### ISSUE THREAD

**Issue by alanski66** [ComBoot/ComBoot#36]
Uploading an attachment produces an error:
 https://www.domain.org/forum/post/reply?f=32&amp;t=30669 404 (Not Found)

console shows:
{MESSAGE_TITLE: "Information", MESSAGE_TEXT: "The requested topic does not exist.",…}
MESSAGE_TEXT
:
"The requested topic does not exist."
MESSAGE_TITLE
:
"Information"
REFRESH_DATA
:
null
S_USER_NOTICE
:
true
S_USER_WARNING
:
false

**Comment by TheZoker** [comment]
Does it work when you use the prosilver theme?

**Comment by alanski66** [comment]
No produces a pop up http error like before with topic not found message.
I noticed the url itslef procudes a 404 👍 https://www.domain.org/forum/post/reply?f=32&amp;t=30678
However the ampersand in url seems to be cause?
If its changed to 👍 https://www.domain.org/forum/post/reply?f=32&t=30678
Then the url resolves

**Comment by TheZoker** [comment]
Ok but then it's not a ComBoot issue, but rather a phpBB issue. Please open a support thread on the phpBB forum:
https://www.phpbb.com/community/viewforum.php?f=556

**Comment by alanski66** [comment]
My bad- settings for PDfs not allowed.
Though have tried jpg's too which are allowed and problem persists
