### ISSUE TITLE
Bootstrap Select! 

### ISSUE THREAD

**Issue by leoforney** [ComBoot/ComBoot#4]
Please try to import Bootstrap Select for selections on everything! It would look much cleaner! :D

**Comment by TheZoker** [comment]
You mean this: http://silviomoreto.github.io/bootstrap-select/ ?

**Comment by leoforney** [comment]
Yes that one :D pleassseeeeee???

**Comment by TheZoker** [comment]
Done ;)

**Comment by leoforney** [comment]
Yesssssssss thanks!

**Comment by TheZoker** [comment]
But sadly, I have to tell you, that this is not working well :/
http://zoker.me/demo/proBoot3/ucp.php?mode=register

Take a look at the language selector....

**Comment by TheZoker** [comment]
But I found a way to work around the issue, so it will be includes ;)

**Comment by leoforney** [comment]
Did you use Bootstrap-Select for bootstrap 3.x.x http://silviomoreto.github.io/bootstrap-select/3/ ???

**Comment by TheZoker** [comment]
Yes the version for Bootstrap 3.

Is caused by <'dd'> and <'dt'> tags, but I will fix
