### ISSUE TITLE
Template is not working

### ISSUE THREAD

**Issue by leoforney** [ComBoot/ComBoot#5]
Thanks for help! I was just having an issue where anything in the template folder isn't working. Everything like the imagesets and the theme is still working but just the Template folder isn't. Can you please fix this soon? I have a fresh new install of phpBB3 with just some forums on it. I have tried deleting all themes but still doesn't work! Thanks so much!

**Comment by TheZoker** [comment]
It's still beta, so there are many bugs... 
Do you use the latest version of the theme? 

Can you send me a link, so I can figure out the problem?

**Comment by leoforney** [comment]
Ja, ich bin mit der neuesten Version. Ich es heute bei rund 2.00 (UTC-6 Zeitzone) aktualisiert. 

Der Link ist https://forums.crystalnetwork.us 

Für jetzt habe ich die Vorlage in einem anderen Stil, der Arbeits bewegt wird. Es ist nur immer wirklich ärgerlich hin und her zu wechseln. 

Hier ist ein Schnappschuss meines ACP: http://gyazo.com/d32863b3958eee5cf06357d61ffdf5d1.png

**Comment by TheZoker** [comment]
What exactly does not work?

Because for me the site seems to work well....

**Comment by leoforney** [comment]
I replaced the template folder from another style that is working. So it should look fine but I have to mess around with the themes. Just look at the second link that I sent.

**Comment by TheZoker** [comment]
What do you mean with "replaced the template folder"?

The normal way of install an phpBB theme is to download it, copy it into your "style" folder and then activate it in the admin panel...

**Comment by leoforney** [comment]
I know I did that. it shows the imageset and in the theme folders. But I just copied the template folder on the proBoot3 to proBoot (My previous style). Just look at the second link.

**Comment by TheZoker** [comment]
I hope I fixed it ;)

**Comment by leoforney** [comment]
Ok let me try :D

**Comment by leoforney** [comment]
Thanks it now works!

**Comment by TheZoker** [comment]
Perfect :)
