### ISSUE TITLE
Cool login screen

### ISSUE THREAD

**Issue by leoforney** [ComBoot/ComBoot#6]
Hello! I think it would be really cool to do one of the two things.

1) Remove the Login panel on every page & make a custom page with just a login page all by itself. And also remove the navbar login form with just a button that redirects to the login page. Like this... http://gyazo.com/64c20b4f1d19e1acd446203c2495b10c

2) Make a dropdown menu for login on every page and remove the login panel on every page. Just like XenForo... http://gyazo.com/ec394277154887a983831ccc929207e8

**Comment by TheZoker** [comment]
I will think about it, but Im not shure, if I will change it....

**Comment by leoforney** [comment]
Okk thanks!

**Comment by k0nsl** [comment]
Good ideas.

**Comment by TheZoker** [comment]
Do you this would be good?
http://bootsnipp.com/snippets/featured/parallax-login-form#

Or: http://bootsnipp.com/snippets/featured/mix-amp-match-login

**Comment by leoforney** [comment]
I think the second one will be better. as the first one is very very trippy. lol

**Comment by leoforney** [comment]
This might interest you though https://www.phpbb.com/community/viewtopic.php?f=74&t=2160243

**Comment by TheZoker** [comment]
http://demo.zoker.me/proBoot3/ucp.php?mode=login ;)

Your login does also look very nice (very close to the xenforo one), but I think, is does not look that beautiful on a bootstrap site...

**Comment by leoforney** [comment]
Nice! Add a div with the id of `loginpanel` and make sure to do http://SITEURL.com/ucp.php?mode=login#loginpanel

**Comment by TheZoker** [comment]
Ok :)

I think tomorrow or the day after tomorrow, I will redesign the registration page, that way and then trow  it up on github :smile:

**Comment by leoforney** [comment]
Actully there is no need for the id of loginpanel though. But you can do http://siteurl.com/up.php?mode=login#start_here and it will be in the center skipping below the navbar.
